name: payment_app
description: "Application Flutter pour la gestion des paiements réguliers - Test Technique DIOKO"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Design
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  lottie: ^3.1.2
  
  # State Management
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  
  # Dependency Injection
  get_it: ^7.7.0
  injectable: ^2.4.4
  
  # Network & API
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  json_annotation: ^4.9.0
  connectivity_plus: ^6.0.5
  
  # Storage & Persistence
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Utilities
  dartz: ^0.10.1
  equatable: ^2.0.5
  intl: ^0.19.0
  logger: ^2.4.0
  
  # File Handling
  file_picker: ^8.0.7
  path_provider: ^2.1.4
  
  # Image Handling
  image_picker: ^1.1.2
  
  # UI Components
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0
  
  # Charts & Graphs
  fl_chart: ^0.68.0
  
  # Animations
  animate_do: ^3.3.4
  
  # Navigation
  go_router: ^14.2.7
  
  # Form Validation
  formz: ^0.7.0
  
  # Date & Time
  table_calendar: ^3.1.2
  
  # Permissions
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  # Code Generation
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.2
  retrofit_generator: ^8.1.2
  hive_generator: ^2.0.1
  
  # Linting & Analysis
  flutter_lints: ^4.0.0
  very_good_analysis: ^6.0.0
  
  # Testing
  bloc_test: ^9.1.7
  mocktail: ^1.0.4
  
  # Integration Testing
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true